name: app_core

description: App core package

version: 1.1.279

homepage: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

publish_to: none

dependencies:
  flutter:
    sdk: flutter

  # Core
  async: ^2.6.1
  url_launcher: ^6.0.4 # ^5.0.2
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  android_id: ^0.3.4
  permission_handler: ^10.4.3
  timeago: ^3.1.0
  intl: ^0.18.1
  flutter_secure_storage: ^8.0.0
  json_annotation: ^4.8.1 # ^4.5.0
  fluttertoast: ^8.2.1
  local_auth: ^2.1.6
  new_version_plus: ^0.0.9 # new_version deprecated
  flutter_local_notifications: ^15.1.1
  flutter_slidable: ^3.0.0
  draggable_widget: ^2.0.0

  # Location
  geolocator: ^10.0.0 # ^7.0.3
  geocoding: ^2.1.0
  google_maps_flutter: ^2.4.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_google_places: ^0.3.0

  lottie: ^2.6.0

  # Photo picker
  image_picker: ^1.0.2

  # QR code scan
  barcode_scan2: ^4.2.4

  # Firebase
  firebase_core_platform_interface: ^4.8.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.6 # ^11.4.4

  gallery_saver: 2.3.2 #2.1.0 # +2.1.1 broken so far
  path_provider: ^2.0.1
  provider: ^6.0.2

  google_fonts: 4.0.3

  # VoIP
  connectycube_flutter_call_kit: 2.3.0

  # Flutter WebRTC
  flutter_webrtc: 0.9.40 #0.6.3 # 0.5.8

  flutter_ringtone_player: ^3.2.0

#  wakelock: ^0.6.2 # 0.5.6 # ^0.5.1
  wakelock_plus: ^1.1.1
  uuid: ^3.0.4

  # Vietnamese language parsing
  tiengviet: ^0.5.0

  # QR code generation
  qr_flutter: ^4.1.0 # ^4.0.0 ^3.2.0

  sliding_up_panel: 2.0.0+1

  confetti: ^0.7.0

  get: ^4.6.3

  get_storage: ^2.0.3

  audioplayers: ^5.1.0

  # Text-to-speech
  flutter_tts: ^3.7.0 # ^3.3.3

  # Cache image
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.2

  flutter_picker: ^2.1.0
  wheel_chooser: ^1.1.2 # ^1.1.0 is buggy

  xml: ^6.3.0

  avatar_glow: ^2.0.2

  flutter_easyloading: ^3.0.5

  syncfusion_flutter_sliders: ^22.2.10

  slider_captcha: ^1.0.0

  flutter_isolate: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: any
  build_resolvers: ^2.3.1
  build_runner: ^2.4.6 #^2.1.5 # ^1.11.5 # ^1.0.0
  json_serializable: ^6.6.2 # 6.2.0 6.1.2 ^3.5.1 # ^3.0.0
  analyzer: ^6.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/img/
    - assets/json/
    - assets/audio/
    - assets/lingo/
  fonts:
    - family: Apercu
      fonts:
        - asset: fonts/ApercuRegular.ttf
        - asset: fonts/ApercuBold.ttf
        - asset: fonts/ApercuItalic.otf
          style: italic
    - family: UberMove
      fonts:
        - asset: fonts/UberMoveMedium.otf
        - asset: fonts/UberMoveBold.otf


#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
