name: app_core

description: App core package

version: 1.1.45

homepage: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

publish_to: none

dependencies:
  flutter:
    sdk: flutter

  # Core
  async: ^2.6.1
  url_launcher: ^6.0.4 # ^5.0.2
  device_info: ^2.0.1
  package_info: ^2.0.0
  permission_handler: ^7.2.0
  timeago: ^3.1.0
  intl: ^0.17.0
  flutter_secure_storage: ^4.2.0
  json_annotation: ^4.4.0
  fluttertoast: ^8.0.7
  local_auth: ^1.1.6
  new_version: ^0.2.0
  flutter_local_notifications: ^6.1.0
  flutter_slidable: ^0.6.0
  draggable_widget: ^2.0.0

  # Location
  geolocator: ^7.0.3
  google_maps_flutter: ^2.0.5
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_google_places: ^0.3.0

  # Photo picker
  image_picker: ^0.8.1

  # QR code scan
  flutter_barcode_scanner: ^2.0.0

  # Firebase
  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.0

  gallery_saver: 2.1.0 # +2.1.1 broken so far
  path_provider: ^2.0.1
  provider: ^6.0.2

  # google_fonts: 2.2.0 # >=2.3.1 requires Flutter SDK >=2.10.0-0
  google_fonts: ^2.3.1

  # VoIP
  connectycube_flutter_call_kit:
    git:
      url: https://github.com/KashinApp/flutter_voip_android.git
    # path: ../flutter_voip_android_local
  flutter_ios_voip_kit:
    git:
      url: https://github.com/KashinApp/flutter_voip_ios.git
    #  ref: 0.0.6
    # path: ../flutter_voip_ios_local

  # Flutter WebRTC
  flutter_webrtc: 0.6.3 # 0.5.8
  flutter_ringtone_player:
    git:
      url: https://github.com/huynhtuanhuy/flutter_ringtone_player.git
    #^3.0.0

  wakelock: 0.5.6 # ^0.5.1
  uuid: ^3.0.4

  # Vietnamese language parsing
  tiengviet: ^0.5.0

  # QR code generation
  qr_flutter: ^4.0.0 # ^3.2.0

  sliding_up_panel: 2.0.0+1

  confetti: ^0.6.0-nullsafety

  get: ^4.3.8
  get_storage: ^2.0.3

  audioplayers: 0.20.1

  flutter_tts: ^3.3.3

  # Cache image
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.0
  flutter_picker: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: any
  build_runner: ^2.1.5 # ^1.11.5 # ^1.0.0
  json_serializable: 6.1.2 # ^3.5.1 # ^3.0.0
  test: ^1.17.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/img/
    - assets/json/
    - assets/audio/
    - assets/lingo/
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
